# Generated by Django 3.0.5 on 2021-06-01 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('representation', models.TextField(unique=True)),
                ('illustration_url', models.TextField()),
                ('matrix', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
